/**
 * CSV for the initial-load data files (RFC 4180).
 *
 * The seed used to read tab-separated files with a plain `split("\t")`. That
 * works only while no value contains the delimiter — and two company names in
 * the source workbook do contain a comma ("Medindustrias, S.A. De C.V."), so
 * the moment the files became comma-separated a naive split would shift every
 * column after them and corrupt the row silently.
 *
 * Hence: every field is written quoted, and reading is quote-aware.
 */

/** Wrap a value in quotes, doubling any quote inside it. */
export function quoteField(value: string): string {
  return `"${value.replace(/"/g, '""')}"`;
}

/** One CSV line with every field quoted. */
export function toCsvRow(fields: readonly string[]): string {
  return fields.map(quoteField).join(",");
}

/** A full CSV document (header + rows), newline-terminated. */
export function toCsv(
  header: readonly string[],
  rows: readonly (readonly string[])[],
): string {
  return `${[toCsvRow(header), ...rows.map(toCsvRow)].join("\n")}\n`;
}

/**
 * Parse a CSV document into rows of fields.
 *
 * Handles quoted fields, commas and newlines inside quotes, and `""` as an
 * escaped quote. Unquoted fields are trimmed; quoted ones are kept verbatim,
 * because the quotes are what declares the value deliberate.
 *
 * Comment lines (`#`) and blank lines are skipped, so the files can keep the
 * provenance header the old `.txt` versions carried.
 */
export function parseCsv(text: string): string[][] {
  const rows: string[][] = [];
  let field = "";
  let row: string[] = [];
  let inQuotes = false;
  let fieldWasQuoted = false;

  // Strip a UTF-8 BOM: Excel writes one and it would otherwise become part of
  // the first field, so `state` would never match the catalog.
  const input = text.replace(/^﻿/, "");

  const endField = () => {
    row.push(fieldWasQuoted ? field : field.trim());
    field = "";
    fieldWasQuoted = false;
  };

  const endRow = () => {
    endField();
    // A trailing newline produces one empty trailing row; drop it, along with
    // comment and blank lines.
    const isBlank = row.length === 1 && row[0] === "";
    const isComment = row[0]?.startsWith("#");
    if (!isBlank && !isComment) rows.push(row);
    row = [];
  };

  for (let i = 0; i < input.length; i += 1) {
    const char = input[i];

    if (inQuotes) {
      if (char === '"') {
        if (input[i + 1] === '"') {
          field += '"';
          i += 1; // consume the escaped pair
        } else {
          inQuotes = false;
        }
      } else {
        field += char;
      }
      continue;
    }

    if (char === '"') {
      inQuotes = true;
      fieldWasQuoted = true;
      continue;
    }
    if (char === ",") {
      endField();
      continue;
    }
    if (char === "\r") continue; // CRLF: handled by the \n that follows
    if (char === "\n") {
      endRow();
      continue;
    }
    field += char;
  }

  // Last line without a trailing newline.
  if (field !== "" || row.length > 0) endRow();

  return rows;
}

/**
 * Parse a CSV that starts with a header row, returning only the data rows.
 *
 * The header is dropped positionally rather than by name: these files are
 * generated by `scripts/generate-seed-data.ts`, so column order is fixed and
 * the header exists to make the file readable, not to be matched against.
 */
export function parseCsvBody(text: string): string[][] {
  const rows = parseCsv(text);
  return rows.slice(1);
}
