import path from "node:path";

/**
 * Seeded roles and their credentials (see prisma/seed.ts / initial_load/seed.ts).
 * Every seeded user shares the same password.
 */
export const SEED_PASSWORD = "password123";

export type Role = "admin" | "fsr" | "client" | "guest";

export interface RoleAccount {
  email: string;
  /** Where the middleware redirects this role after landing on "/". */
  defaultPath: string;
}

export const ACCOUNTS: Record<Role, RoleAccount> = {
  admin: { email: "admin@opusinspection.com", defaultPath: "/admin" },
  fsr: { email: "fsr@opusinspection.com", defaultPath: "/fsr" },
  client: { email: "client@opusinspection.com", defaultPath: "/client" },
  guest: { email: "guest@opusinspection.com", defaultPath: "/guest" },
};

export const ROLES = Object.keys(ACCOUNTS) as Role[];

/**
 * Path to the persisted Playwright storage state for a role. Generated by
 * e2e/auth.setup.ts and consumed by specs via `test.use({ storageState })`.
 */
export function authFile(role: Role): string {
  return path.join(__dirname, "..", ".auth", `${role}.json`);
}
