import path from "node:path";

/**
 * Accounts used by the suite, resolved from the environment.
 *
 * Nothing is hardcoded here: emails and the shared password come from
 * `config/e2e.env` (tracked, throwaway values pointing at the disposable
 * container) and can be overridden by `config/e2e.local.env` (gitignored) when
 * you want to run against your own database and your own accounts.
 *
 * `e2e/db.setup.ts` provisions any configured account that does not exist, so
 * the suite is self-sufficient on a freshly created database.
 */

export type Role = "admin" | "fsr" | "client" | "guest";

export interface RoleAccount {
  email: string;
  password: string;
  name: string;
  /** Role name in the `Role` catalog. */
  roleName: string;
  /** Where the middleware redirects this role after landing on "/". */
  defaultPath: string;
}

function required(name: string): string {
  const value = process.env[name];
  if (!value) {
    throw new Error(
      `Falta la variable de entorno ${name}. Ejecuta los e2e con ` +
        "`npm run test:e2e`, que carga config/e2e.env.",
    );
  }
  return value;
}

/** Shared password for every e2e account. */
export const E2E_PASSWORD = (): string => required("E2E_PASSWORD");

const DEFINITIONS: Record<
  Role,
  { envKey: string; name: string; roleName: string; defaultPath: string }
> = {
  admin: {
    envKey: "E2E_ADMIN_EMAIL",
    name: "E2E Admin",
    roleName: "ADMINISTRADOR",
    defaultPath: "/admin",
  },
  fsr: {
    envKey: "E2E_FSR_EMAIL",
    name: "E2E FSR",
    roleName: "FSR",
    defaultPath: "/fsr",
  },
  client: {
    envKey: "E2E_CLIENT_EMAIL",
    name: "E2E Client",
    roleName: "CLIENT",
    defaultPath: "/client",
  },
  guest: {
    envKey: "E2E_GUEST_EMAIL",
    name: "E2E Guest",
    roleName: "GUEST",
    defaultPath: "/guest",
  },
};

export const ROLES = Object.keys(DEFINITIONS) as Role[];

/**
 * Resolve a role's account. Read lazily so a missing variable fails inside a
 * test with a clear message instead of crashing config collection.
 */
export function account(role: Role): RoleAccount {
  const def = DEFINITIONS[role];
  return {
    email: required(def.envKey),
    password: required("E2E_PASSWORD"),
    name: def.name,
    roleName: def.roleName,
    defaultPath: def.defaultPath,
  };
}

/** Where the middleware sends this role after login. Safe to read at collection time. */
export function defaultPathFor(role: Role): string {
  return DEFINITIONS[role].defaultPath;
}

/**
 * Path to the persisted Playwright storage state for a role. Generated by
 * e2e/auth.setup.ts and consumed by specs via `test.use({ storageState })`.
 */
export function authFile(role: Role): string {
  return path.join(__dirname, "..", ".auth", `${role}.json`);
}
