import { expect, type Page, test } from "@playwright/test";
import { authFile } from "./fixtures/auth";
import { db, uniqueSuffix } from "./fixtures/db";
import { fillStable } from "./fixtures/forms";

/**
 * The role split (ROOT / ADMIN_OPERACION / ADMIN_VACACIONES / EMPLEADO).
 *
 * Two properties matter here and neither is visible from a unit test:
 *
 *  1. A module administrator reaches their module and NOTHING else — including
 *     the screens that hand out roles. The old `ADMINISTRADOR` name meant four
 *     unrelated things at once, and the one worth protecting is this.
 *  2. ROOT still reaches everything. That is the proof the migration, which
 *     renamed ADMINISTRADOR into ROOT rather than recreating it, took nobody's
 *     access away.
 *
 * Accounts are created here rather than in `config/e2e.env`, so the spec stays
 * self-sufficient and does not widen the shared fixture set.
 */

test.describe.configure({ mode: "serial" });

const PASSWORD = "Rbac123!";

interface Actor {
  email: string;
  password: string;
}

async function makeUser(roleNames: string[]): Promise<Actor> {
  const suffix = uniqueSuffix();
  const email = `e2e.rbac.${suffix}@opusinspection.com`;

  const [roles, activeStatus] = await Promise.all([
    db().role.findMany({ where: { name: { in: roleNames } } }),
    db().userStatus.findFirstOrThrow({ where: { name: "ACTIVO" } }),
  ]);
  if (roles.length !== roleNames.length) {
    throw new Error(
      `Faltan roles ${roleNames.join(", ")} en el catálogo. ¿Corrió el seed?`,
    );
  }

  // bcrypt hash of PASSWORD, generated by the app's own hasher at setup time.
  const { hashPassword } = await import("../src/lib/security/hash");

  await db().user.create({
    data: {
      email,
      name: `E2E RBAC ${roleNames.join("+")} ${suffix}`,
      password: await hashPassword(PASSWORD),
      userStatusId: activeStatus.id,
      userRoles: { create: roles.map((r) => ({ roleId: r.id })) },
    },
  });

  return { email, password: PASSWORD };
}

/** Sign in through the real form, so the JWT is built the way production does. */
async function signIn(page: Page, actor: Actor) {
  await page.goto("/login");
  await fillStable(page.locator("#email"), actor.email);
  await fillStable(page.locator("#password"), actor.password);
  await page.getByRole("button", { name: /Iniciar|Entrar|Ingresar/i }).click();
  await page.waitForURL((url) => !url.pathname.startsWith("/login"), {
    timeout: 15_000,
  });
}

/**
 * The navigation sidebar.
 *
 * Addressed by `data-sidebar` rather than by the `navigation` role: the shadcn
 * Sidebar renders plain containers with no landmark, so `getByRole` finds
 * nothing.
 */
function menu(page: Page) {
  return page.locator('[data-sidebar="sidebar"]').first();
}

/** Follow a path and report where the app actually left us. */
async function landsOn(page: Page, path: string): Promise<string> {
  await page.goto(path, { waitUntil: "networkidle" });
  return new URL(page.url()).pathname;
}

test.describe("ADMIN_VACACIONES", () => {
  let actor: Actor;

  test.beforeAll(async () => {
    actor = await makeUser(["ADMIN_VACACIONES"]);
  });

  test("entra a su módulo y a sus propias vacaciones", async ({ page }) => {
    await signIn(page, actor);

    expect(await landsOn(page, "/admin/vacations")).toBe("/admin/vacations");
    expect(await landsOn(page, "/vacations")).toBe("/vacations");
  });

  test("NO alcanza operación ni la administración de roles", async ({
    page,
  }) => {
    await signIn(page, actor);

    // Administering vacations is not a licence to administer anything else,
    // and above all not to hand out roles.
    for (const path of [
      "/admin/incidents",
      "/admin/tracking",
      "/admin/users",
      "/admin/roles",
      "/admin/permissions",
    ]) {
      expect(await landsOn(page, path), path).toBe("/unauthorized");
    }
  });

  test("el menú no ofrece lo que no puede abrir", async ({ page }) => {
    await signIn(page, actor);
    await page.goto("/admin/vacations", { waitUntil: "networkidle" });

    const nav = menu(page);
    await expect(nav.getByRole("link", { name: "Solicitudes" })).toBeVisible();
    await expect(
      nav.getByRole("link", { name: "Mis Vacaciones" }),
    ).toBeVisible();

    // The sections it cannot reach are absent, not merely disabled.
    await expect(nav.getByRole("link", { name: "Roles" })).toHaveCount(0);
    await expect(nav.getByRole("link", { name: "Usuarios" })).toHaveCount(0);
    await expect(nav.getByRole("link", { name: "Incidentes" })).toHaveCount(0);
  });
});

test.describe("ADMIN_VACACIONES + FSR", () => {
  let actor: Actor;

  test.beforeAll(async () => {
    actor = await makeUser(["ADMIN_VACACIONES", "FSR"]);
  });

  test("obtiene la UNIÓN de ambos roles en un solo menú", async ({ page }) => {
    await signIn(page, actor);

    // Both halves, reachable at once — this is the whole point of multi-role.
    expect(await landsOn(page, "/admin/vacations")).toBe("/admin/vacations");
    expect(await landsOn(page, "/fsr/assignments")).toBe("/fsr/assignments");

    const nav = menu(page);
    await expect(nav.getByRole("link", { name: "Solicitudes" })).toBeVisible();
    await expect(
      nav.getByRole("link", { name: "Mis Asignaciones" }),
    ).toBeVisible();

    // And still nothing it was never granted.
    await expect(nav.getByRole("link", { name: "Roles" })).toHaveCount(0);
    expect(await landsOn(page, "/admin/roles")).toBe("/unauthorized");
  });
});

test.describe("EMPLEADO", () => {
  let actor: Actor;

  test.beforeAll(async () => {
    actor = await makeUser(["EMPLEADO"]);
  });

  test("solo llega a sus vacaciones y a su perfil", async ({ page }) => {
    await signIn(page, actor);

    expect(await landsOn(page, "/vacations")).toBe("/vacations");
    expect(await landsOn(page, "/profile")).toBe("/profile");

    for (const path of ["/admin", "/admin/vacations", "/fsr", "/client"]) {
      expect(await landsOn(page, path), path).toBe("/unauthorized");
    }
  });
});

test.describe("CLIENT", () => {
  test.use({ storageState: authFile("client") });

  test("no tiene vacaciones: es la cuenta del centro, no una persona", async ({
    page,
  }) => {
    expect(await landsOn(page, "/vacations")).toBe("/unauthorized");
  });
});

test.describe("ROOT", () => {
  test.use({ storageState: authFile("admin") });

  test("conserva acceso a todo tras la migración", async ({ page }) => {
    // The migration renamed the ADMINISTRADOR row into ROOT instead of creating
    // a new one, precisely so no existing administrator would be locked out.
    for (const path of [
      "/admin",
      "/admin/incidents",
      "/admin/tracking",
      "/admin/vacations",
      "/admin/users",
      "/admin/roles",
      "/admin/permissions",
      "/vacations",
      "/fsr",
    ]) {
      expect(await landsOn(page, path), path).toBe(path);
    }
  });
});
