name: Deploy Frontend

on:
  push:
    paths:
      - "frontend/**"
    branches: ["main"]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # No build step here - Docker will handle the build
      - name: Package application
        working-directory: frontend
        run: |
          # Package source code for Docker to build
          tar -cf ../deploy.tar \
            Dockerfile \
            captain-definition.json \
            package*.json \
            next.config.ts \
            tsconfig.json \
            tailwind.config.ts \
            postcss.config.mjs \
            components.json \
            src \
            public

      - name: Deploy to CapRover
        uses: caprover/deploy-from-github@v1.1.2
        with:
          server: ${{ secrets.CAPROVER_SERVER }}
          app: ${{ secrets.CAPROVER_FRONTEND_APP_NAME }}
          token: ${{ secrets.CAPROVER_FRONTEND_APP_TOKEN }}
